image: dregistry.gahr.dev/ci-go-runner

# Keep vendor dependencies between jobs (results in lower build times)
cache: &global_cache
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
  policy: pull

stages:
  - dependencies
  - test
  - build
  - deploy

make dependencies:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
  stage: dependencies
  script:
    - make dep
    - ls -l
  tags:
    - GameBase
    - docker

unit_tests:
  stage: test
  script:
    - make test
  tags:
    - GameBase
    - docker

race_detector:
  stage: test
  script:
    - make race
  tags:
    - GameBase
    - docker

memory_sanitizer:
  stage: test
  script:
    - make msan
  tags:
    - GameBase
    - docker

code_coverage:
  stage: test
  script:
    - make coverage
  tags:
    - GameBase
    - docker

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master
  artifacts:
    paths:
      - coverage.html
  tags:
    - GameBase
    - docker

lint_code:
  stage: test
  script:
    - make lint
  allow_failure: true
  tags:
    - GameBase
    - docker

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
    - out
  tags:
    - GameBase
    - docker

deploy_server:
  stage: deploy
  before_script:
    - sleep 1
  script:
    - screen -S backend -X stuff ^C || true
    - screen -dmS backend bash -c "env GIN_MODE=release PORT=42069 out/server; while true; do sleep 1; done"
  only:
    - master
  tags:
    - GameBase
    - shell

pages:
  stage: deploy
  before_script:
    - sleep 1
  script:
    - mkdir public
    - cp coverage.html public
  artifacts:
    paths:
      - public/
  only:
    - master
  tags:
    - GameBase
