# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:80/gs/status
Accept: application/json

###
GET http://localhost:80/gs/start/42
Accept: application/json

###
GET http://localhost:80/gs/stop/42
Accept: application/json

###
GET http://localhost:80/gs/restart/42
Accept: application/json

###
POST http://localhost:80/gs/deploy
Accept: application/json

{
  "TemplatePath": "nginx:latest"
}

###
DELETE http://localhost:80/gs/destroy/42
Accept: application/json

###
POST http://localhost:80/auth/login
Accept: application/json

{
  "email": "etaloof@gmail.com",
  "password": "string"
}

###
POST http://localhost:80/auth/register
Accept: application/json

{
  "fullName": "Stefan Lukas",
  "email": "etaloof@gmail.com",
  "password": "string",
  "confirmPassword": "string"
}

###

DELETE http://localhost:80/auth/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImQ2ZWU0YWIwLTY5ZmYtNGU2ZC05YzEzLWU4NzVhYjdhZTVjNCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTU5MzM5NDA4NSwidXNlcl9lbWFpbCI6ImV0YWxvb2ZAZ21haWwuY29tIn0.g6VXo3x9ypNy_DP0QfexUT-8EJhH6NN2owPq322ePPw