/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 1.0.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

// ConfigureContainer - Configure a game server based on POST body
func ConfigureContainer(c *gin.Context) {
	ConfigureContainer_(c)
}

// DeleteContainer - Delete deployment of game server
func DeleteContainer(c *gin.Context) {
	DeleteContainer_(c)
}

// DeployContainer - Deploy a game server based on POST body
func DeployContainer(c *gin.Context) {
	DeployContainer_(c)
}

// GetStatus - Query status of all deployments
func GetStatus(c *gin.Context) {
	GetStatus_(c)
}

// ListImages - Get a list of all available game server images
func ListImages(c *gin.Context) {
	ListImages_(c)
}

// RestartContainer - Restart a game server/container
func RestartContainer(c *gin.Context) {
	RestartContainer_(c)
}

// StartContainer - Start a game server/container
func StartContainer(c *gin.Context) {
	StartContainer_(c)
}

// StopContainer - Stop a game server/container
func StopContainer(c *gin.Context) {
	StopContainer_(c)
}
