/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.3.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

// AuthLoginPost - Login a user and return a JWT with the user object
func AuthLoginPost(c *gin.Context) {
	NewHttpRequestProcessingChain().Login(c)
}

// AuthLogoutDelete - Invalidate the passed JWT
func AuthLogoutDelete(c *gin.Context) {
	NewHttpRequestProcessingChain().Logout(c)
}

// AuthRegisterPost - Register a user and return a JWT with the user object
func AuthRegisterPost(c *gin.Context) {
	NewHttpRequestProcessingChain().Register(c)
}
