/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.1.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserRegister struct {

	// Full name of the user
	FullName string `json:"fullName,omitempty"`

	// Email address of the user
	Email string `json:"email"`

	// The password of the user
	Password string `json:"password"`

	// The password confirmation of the user (must be equal to password)
	ConfirmPassword string `json:"confirmPassword"`
}
