/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.1.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GameContainerConfigurationResourcesPorts - Ports to be allocated
type GameContainerConfigurationResourcesPorts struct {

	Tcp []int32 `json:"tcp,omitempty"`

	Udp []int32 `json:"udp,omitempty"`
}
