/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.3.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserProfilePassword struct {

	// Old password of the user as a confirmation step
	Old string `json:"old,omitempty"`

	// New desired password of the user
	New string `json:"new,omitempty"`
}
