/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.3.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserProfile struct {

	// Username of the user
	Username string `json:"username,omitempty"`

	// E-mail address of the user
	Email string `json:"email,omitempty"`

	Password UserProfilePassword `json:"password,omitempty"`

	// E-mail address of the Gravatar to be used
	Gravatar string `json:"gravatar,omitempty"`
}
