/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.3.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PortMapping struct {

	Protocol Protocol `json:"protocol"`

	// Externally exposed Port Number
	NodePort int32 `json:"nodePort"`

	// Internal Port Number routed to Container
	ContainerPort int32 `json:"containerPort"`
}
