/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 2.0.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	http2 "gitlab.tandashi.de/GameBase/gamebase-backend/http"
	"gitlab.tandashi.de/GameBase/gamebase-backend/kubernetes"
	"net/http"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	corsConfig := cors.DefaultConfig()
	corsConfig.AllowAllOrigins = true
	corsConfig.AddAllowHeaders("Authorization")
	router.Use(cors.New(corsConfig))
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"AuthLoginPost",
		http.MethodPost,
		"/auth/login",
		AuthLoginPost,
	},

	{
		"ConfigureContainer",
		http.MethodPost,
		"/gs/configure/:id",
		ConfigureContainer,
	},

	{
		"DeleteContainer",
		http.MethodDelete,
		"/gs/destroy/:id",
		DeleteContainer,
	},

	{
		"DeployContainer",
		http.MethodPost,
		"/gs/deploy",
		DeployContainer,
	},

	{
		"GetStatus",
		http.MethodGet,
		"/gs/status",
		GetStatus,
	},

	{
		"ListTemplates",
		http.MethodGet,
		"/gs/templates",
		ListTemplates,
	},

	{
		"RestartContainer",
		http.MethodGet,
		"/gs/restart/:id",
		RestartContainer,
	},

	{
		"StartContainer",
		http.MethodGet,
		"/gs/start/:id",
		StartContainer,
	},

	{
		"StopContainer",
		http.MethodGet,
		"/gs/stop/:id",
		StopContainer,
	},
}

var Api = kubernetes.NewAPI()
var authenticator = http2.NewHttpRequestAuthenticator()
