/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 1.0.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ConfigureContainer - Configure a game server based on POST body
func ConfigureContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteContainer - Delete deployment of game server
func DeleteContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeployContainer - Deploy a game server based on POST body
func DeployContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetStatus - Query status of a container
func GetStatus(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RestartContainer - Restart a game server/container
func RestartContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// StartContainer - Start a game server/container
func StartContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// StopContainer - Stop a game server/container
func StopContainer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
