/*
 * GameBase Communication API
 *
 * This is the REST API used as an communication layer between backend and frontend.
 *
 * API version: 1.0.0
 * Contact: gamebase@gahr.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/humenius/GameBase-Comm-API/1.0.0/",
		Index,
	},

	{
		"ConfigureContainer",
		http.MethodPost,
		"/humenius/GameBase-Comm-API/1.0.0/api/configure",
		ConfigureContainer,
	},

	{
		"DeleteContainer",
		http.MethodDelete,
		"/humenius/GameBase-Comm-API/1.0.0/api/destroy/:id",
		DeleteContainer,
	},

	{
		"DeployContainer",
		http.MethodPost,
		"/humenius/GameBase-Comm-API/1.0.0/api/deploy",
		DeployContainer,
	},

	{
		"GetStatus",
		http.MethodGet,
		"/humenius/GameBase-Comm-API/1.0.0/api",
		GetStatus,
	},

	{
		"RestartContainer",
		http.MethodGet,
		"/humenius/GameBase-Comm-API/1.0.0/api/restart/:id",
		RestartContainer,
	},

	{
		"StartContainer",
		http.MethodGet,
		"/humenius/GameBase-Comm-API/1.0.0/api/start/:id",
		StartContainer,
	},

	{
		"StopContainer",
		http.MethodGet,
		"/humenius/GameBase-Comm-API/1.0.0/api/stop/:id",
		StopContainer,
	},
}
